spring:
  application:
    name: restchat
#  datasource:
#    url: jdbc:postgresql://localhost:5432/restchat_db0
#    username: developer
#    password: password

logging:
  file: logs/app.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    root: INFO
