version: '3'
services:
  app:
    image: restchat:latest
    container_name: restchat
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/restchat_db
      - SPRING_DATASOURCE_USERNAME=username
      - SPRING_DATASOURCE_PASSWORD=password
    ports:
      - "8080:8080"

  postgres:
    image: postgres:12
    container_name: postgres
    ports:
      - "5438:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: restchat_db