version: '3.7'
services:

  postgres:
    image: postgres:12
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_conf:/etc/postgresql
      - postgres_log:/var/log/postgresql

volumes:
  postgres_data:
  postgres_conf:
  postgres_log: